### ISSUE TITLE
XGBoost parameters

### ISSUE THREAD

**Issue by LornaAS93** [jjbrophy47/tree_influence#2]
When trying to run an explainer (I've tried LeafInfluence and BoostIn) on an XGBoost model, I get an error if the model does not have a reg_alpha=0, tree_method='hist' and scale_pos_weight=1. The errors are all arising from assert statements in parser_xgb. Are these necessary, as it would be good to be able to test models with different hyperparameters?

**Comment by jjbrophy47** [comment]
Hi LornaAs93, thanks for reaching out about this. Those assertions were part of a legacy version of this package. I've pushed a new version, 0.1.4, which should fix this issue. Please let me know if you have further issues.
