### ISSUE TITLE
ModuleNotFoundError: No module named 'tree_influence.explainers.parsers._tree32'

### ISSUE THREAD

**Issue by S2378kmeth** [jjbrophy47/tree_influence#3]
i tried running this -- from tree_influence.explainers import BoostIn

getting said error. I don't know what could be causing this error ? Please help.

The only difference that I see is that - _tree32 is a .c file compared to other .py files. But for this I already have installed cython.

**Comment by S2378kmeth** [comment]
when I tried this on google colab - there I am getting another error. I tired changing versions of python but that didn't help. In summary I am not able to use this package any where. :( 

ImportError: numpy.core.multiarray failed to import

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by ZaydH** [comment]
@S2378kmeth Can you share more details on your setup and a MWE? I tried on my setup:

* OS: MacOS Ventura 13.2.1 and PopOS 22.04
* Python Version: 3.10.10
* Python Distribution: `pip`

I ran `ipython` and then called `from tree_influence.explainers import BoostIn` and did not get an error.
